// sample-data.js - ILLUSTRATIVE / SAMPLE DATA ONLY.
// Every value below is made up for demonstration. No real MCL machines,
// operators or fuel figures are used. Litres above norm is NOT stored here:
// the dashboard works it out as Actual minus Norm.
window.DIESEL_DATA_LABEL = "Illustrative / Sample Data";
window.DIESEL_DATA = [
  {date:"2026-09-01", type:"Dumper", eq:"DT-03", operator:"OP-107", shift:"B Shift", norm:240, actual:224, fuelPoint:"Fuel Point-03", status:"Closed", action:"No Action", remarks:"Within norm"},
  {date:"2026-09-01", type:"Dumper", eq:"DT-07", operator:"OP-115", shift:"A Shift", norm:260, actual:249, fuelPoint:"Fuel Point-02", status:"Closed", action:"No Action", remarks:"Within norm"},
  {date:"2026-09-01", type:"Other", eq:"GR-01", operator:"OP-117", shift:"A Shift", norm:110, actual:93, fuelPoint:"Fuel Point-04", status:"Closed", action:"No Action", remarks:"Within norm"},
  {date:"2026-09-01", type:"Loader", eq:"LD-02", operator:"OP-113", shift:"B Shift", norm:190, actual:164, fuelPoint:"Fuel Point-04", status:"Closed", action:"No Action", remarks:"Within norm"},
  {date:"2026-09-02", type:"Dumper", eq:"DT-02", operator:"OP-102", shift:"A Shift", norm:240, actual:232, fuelPoint:"Fuel Point-03", status:"Closed", action:"No Action", remarks:"Within norm"},
  {date:"2026-09-03", type:"Dumper", eq:"DT-01", operator:"OP-101", shift:"C Shift", norm:240, actual:231, fuelPoint:"Fuel Point-01", status:"Closed", action:"No Action", remarks:"Within norm"},
  {date:"2026-09-03", type:"Dumper", eq:"DT-02", operator:"OP-101", shift:"C Shift", norm:240, actual:233, fuelPoint:"Fuel Point-03", status:"Closed", action:"No Action", remarks:"Within norm"},
  {date:"2026-09-03", type:"Dumper", eq:"DT-04", operator:"OP-103", shift:"B Shift", norm:240, actual:218, fuelPoint:"Fuel Point-02", status:"Closed", action:"No Action", remarks:"Within norm"},
  {date:"2026-09-04", type:"Shovel", eq:"SH-02", operator:"OP-104", shift:"A Shift", norm:420, actual:448, fuelPoint:"Fuel Point-01", status:"Closed", action:"No Action", remarks:"Minor; long loading cycle"},
  {date:"2026-09-04", type:"Shovel", eq:"SH-02", operator:"OP-104", shift:"B Shift", norm:420, actual:416, fuelPoint:"Fuel Point-01", status:"Closed", action:"No Action", remarks:"Within norm"},
  {date:"2026-09-05", type:"Dumper", eq:"DT-07", operator:"OP-115", shift:"B Shift", norm:260, actual:235, fuelPoint:"Fuel Point-02", status:"Closed", action:"No Action", remarks:"Within norm"},
  {date:"2026-09-06", type:"Dumper", eq:"DT-01", operator:"OP-101", shift:"B Shift", norm:240, actual:266, fuelPoint:"Fuel Point-01", status:"Closed", action:"No Action", remarks:"Minor variation"},
  {date:"2026-09-07", type:"Shovel", eq:"SH-01", operator:"OP-105", shift:"C Shift", norm:420, actual:455, fuelPoint:"Fuel Point-01", status:"Closed", action:"No Action", remarks:"Waiting time with engine running"},
  {date:"2026-09-08", type:"Dumper", eq:"DT-03", operator:"OP-107", shift:"C Shift", norm:240, actual:312, fuelPoint:"Fuel Point-03", status:"Closed", action:"Retrain Operator", remarks:"Long idling at loading point"},
  {date:"2026-09-08", type:"Shovel", eq:"SH-02", operator:"OP-108", shift:"B Shift", norm:420, actual:414, fuelPoint:"Fuel Point-01", status:"Closed", action:"No Action", remarks:"Within norm"},
  {date:"2026-09-09", type:"Dumper", eq:"DT-05", operator:"OP-109", shift:"A Shift", norm:240, actual:270, fuelPoint:"Fuel Point-01", status:"Closed", action:"No Action", remarks:"Minor variation"},
  {date:"2026-09-09", type:"Shovel", eq:"SH-03", operator:"OP-106", shift:"A Shift", norm:420, actual:417, fuelPoint:"Fuel Point-03", status:"Closed", action:"No Action", remarks:"Within norm"},
  {date:"2026-09-11", type:"Dozer", eq:"DZ-01", operator:"OP-118", shift:"A Shift", norm:260, actual:315, fuelPoint:"Fuel Point-04", status:"Closed", action:"Maintenance Check", remarks:"Air filter cleaned"},
  {date:"2026-09-12", type:"Loader", eq:"LD-02", operator:"OP-113", shift:"A Shift", norm:190, actual:220, fuelPoint:"Fuel Point-04", status:"Closed", action:"No Action", remarks:"Minor variation"},
  {date:"2026-09-12", type:"Shovel", eq:"SH-02", operator:"OP-104", shift:"B Shift", norm:420, actual:460, fuelPoint:"Fuel Point-01", status:"Closed", action:"Check Fuel Issue", remarks:"Fuel issue records verified"},
  {date:"2026-09-13", type:"Loader", eq:"LD-02", operator:"OP-113", shift:"C Shift", norm:190, actual:165, fuelPoint:"Fuel Point-04", status:"Closed", action:"No Action", remarks:"Within norm"},
  {date:"2026-09-14", type:"Dumper", eq:"DT-07", operator:"OP-112", shift:"A Shift", norm:260, actual:294, fuelPoint:"Fuel Point-02", status:"Closed", action:"No Action", remarks:"Within tolerance after review"},
  {date:"2026-09-15", type:"Dumper", eq:"DT-02", operator:"OP-101", shift:"B Shift", norm:240, actual:325, fuelPoint:"Fuel Point-03", status:"Pending", action:"Check Fuel Issue", remarks:"Fuel issued above usual quantity"},
  {date:"2026-09-15", type:"Dumper", eq:"DT-07", operator:"OP-112", shift:"C Shift", norm:260, actual:244, fuelPoint:"Fuel Point-02", status:"Closed", action:"No Action", remarks:"Within norm"},
  {date:"2026-09-15", type:"Loader", eq:"LD-02", operator:"OP-113", shift:"B Shift", norm:190, actual:163, fuelPoint:"Fuel Point-04", status:"Closed", action:"No Action", remarks:"Within norm"},
  {date:"2026-09-15", type:"Shovel", eq:"SH-02", operator:"OP-108", shift:"A Shift", norm:420, actual:393, fuelPoint:"Fuel Point-01", status:"Closed", action:"No Action", remarks:"Within norm"},
  {date:"2026-09-16", type:"Dozer", eq:"DZ-01", operator:"OP-118", shift:"B Shift", norm:260, actual:308, fuelPoint:"Fuel Point-04", status:"Closed", action:"No Action", remarks:"Heavy ripping in hard strata"},
  {date:"2026-09-17", type:"Dumper", eq:"DT-03", operator:"OP-107", shift:"A Shift", norm:240, actual:335, fuelPoint:"Fuel Point-03", status:"Closed", action:"Retrain Operator", remarks:"Idling noted by shift supervisor"},
  {date:"2026-09-17", type:"Dumper", eq:"DT-07", operator:"OP-115", shift:"A Shift", norm:260, actual:247, fuelPoint:"Fuel Point-02", status:"Closed", action:"No Action", remarks:"Within norm"},
  {date:"2026-09-17", type:"Shovel", eq:"SH-02", operator:"OP-104", shift:"A Shift", norm:420, actual:412, fuelPoint:"Fuel Point-01", status:"Closed", action:"No Action", remarks:"Within norm"},
  {date:"2026-09-18", type:"Dumper", eq:"DT-03", operator:"OP-107", shift:"C Shift", norm:240, actual:212, fuelPoint:"Fuel Point-03", status:"Closed", action:"No Action", remarks:"Within norm"},
  {date:"2026-09-18", type:"Dumper", eq:"DT-07", operator:"OP-115", shift:"C Shift", norm:260, actual:244, fuelPoint:"Fuel Point-02", status:"Closed", action:"No Action", remarks:"Within norm"},
  {date:"2026-09-18", type:"Dozer", eq:"DZ-01", operator:"OP-118", shift:"B Shift", norm:260, actual:330, fuelPoint:"Fuel Point-04", status:"Closed", action:"Maintenance Check", remarks:"Checked for leaks; none found"},
  {date:"2026-09-18", type:"Shovel", eq:"SH-03", operator:"OP-106", shift:"B Shift", norm:420, actual:442, fuelPoint:"Fuel Point-03", status:"Closed", action:"No Action", remarks:"Minor variation"},
  {date:"2026-09-19", type:"Loader", eq:"LD-01", operator:"OP-116", shift:"A Shift", norm:190, actual:228, fuelPoint:"Fuel Point-02", status:"Closed", action:"No Action", remarks:"Extra rehandling of overburden"},
  {date:"2026-09-19", type:"Shovel", eq:"SH-02", operator:"OP-108", shift:"A Shift", norm:420, actual:472, fuelPoint:"Fuel Point-01", status:"Closed", action:"Maintenance Check", remarks:"Hydraulic filter replaced"},
  {date:"2026-09-20", type:"Dumper", eq:"DT-05", operator:"OP-110", shift:"C Shift", norm:240, actual:285, fuelPoint:"Fuel Point-01", status:"Closed", action:"Check Fuel Issue", remarks:"Fuel slip re-checked"},
  {date:"2026-09-21", type:"Dumper", eq:"DT-06", operator:"OP-111", shift:"A Shift", norm:260, actual:257, fuelPoint:"Fuel Point-03", status:"Closed", action:"No Action", remarks:"Within norm"},
  {date:"2026-09-21", type:"Dumper", eq:"DT-06", operator:"OP-111", shift:"B Shift", norm:260, actual:352, fuelPoint:"Fuel Point-03", status:"Closed", action:"Check Fuel Issue", remarks:"Meter calibration difference found"},
  {date:"2026-09-21", type:"Shovel", eq:"SH-01", operator:"OP-105", shift:"B Shift", norm:420, actual:417, fuelPoint:"Fuel Point-01", status:"Closed", action:"No Action", remarks:"Within norm"},
  {date:"2026-09-22", type:"Dumper", eq:"DT-07", operator:"OP-112", shift:"B Shift", norm:260, actual:318, fuelPoint:"Fuel Point-02", status:"Closed", action:"Check Fuel Issue", remarks:"Fuel issue slip checked; hour-meter matched"},
  {date:"2026-09-23", type:"Shovel", eq:"SH-02", operator:"OP-104", shift:"B Shift", norm:420, actual:486, fuelPoint:"Fuel Point-01", status:"Under Inspection", action:"Inspect Machine", remarks:"Engine load check under way"},
  {date:"2026-09-23", type:"Other", eq:"WT-01", operator:"OP-117", shift:"C Shift", norm:95, actual:113, fuelPoint:"Fuel Point-04", status:"Closed", action:"No Action", remarks:"Extra water trips"},
  {date:"2026-09-24", type:"Dumper", eq:"DT-06", operator:"OP-111", shift:"C Shift", norm:260, actual:257, fuelPoint:"Fuel Point-03", status:"Closed", action:"No Action", remarks:"Within norm"},
  {date:"2026-09-24", type:"Dumper", eq:"DT-07", operator:"OP-112", shift:"A Shift", norm:260, actual:239, fuelPoint:"Fuel Point-02", status:"Closed", action:"No Action", remarks:"Within norm"},
  {date:"2026-09-24", type:"Dumper", eq:"DT-08", operator:"OP-114", shift:"C Shift", norm:260, actual:324, fuelPoint:"Fuel Point-02", status:"Closed", action:"Check Fuel Issue", remarks:"Fuel issue slip verified"},
  {date:"2026-09-25", type:"Dumper", eq:"DT-03", operator:"OP-107", shift:"B Shift", norm:240, actual:358, fuelPoint:"Fuel Point-03", status:"Pending", action:"Retrain Operator", remarks:"Idling above 2 hours reported"},
  {date:"2026-09-25", type:"Other", eq:"GR-01", operator:"OP-117", shift:"A Shift", norm:110, actual:134, fuelPoint:"Fuel Point-04", status:"Pending", action:"Check Fuel Issue", remarks:"Awaiting supervisor sign-off"},
  {date:"2026-09-26", type:"Other", eq:"GR-01", operator:"OP-117", shift:"B Shift", norm:110, actual:98, fuelPoint:"Fuel Point-04", status:"Closed", action:"No Action", remarks:"Within norm"},
  {date:"2026-09-26", type:"Shovel", eq:"SH-01", operator:"OP-105", shift:"A Shift", norm:420, actual:460, fuelPoint:"Fuel Point-01", status:"Under Inspection", action:"Inspect Machine", remarks:"Under review by E&M"},
  {date:"2026-09-27", type:"Dumper", eq:"DT-07", operator:"OP-112", shift:"B Shift", norm:260, actual:356, fuelPoint:"Fuel Point-02", status:"Under Inspection", action:"Inspect Machine", remarks:"Repeat excess; E&M inspection started"},
  {date:"2026-09-27", type:"Dumper", eq:"DT-07", operator:"OP-115", shift:"C Shift", norm:260, actual:372, fuelPoint:"Fuel Point-02", status:"Pending", action:"Inspect Machine", remarks:"High consumption continued on next shift"},
  {date:"2026-09-27", type:"Shovel", eq:"SH-02", operator:"OP-104", shift:"A Shift", norm:420, actual:508, fuelPoint:"Fuel Point-01", status:"Pending", action:"Inspect Machine", remarks:"Excess rising week on week"},
  {date:"2026-09-28", type:"Dumper", eq:"DT-07", operator:"OP-112", shift:"A Shift", norm:260, actual:428, fuelPoint:"Fuel Point-02", status:"Pending", action:"Maintenance Check", remarks:"Possible fuel-line leak; check injectors"},
  {date:"2026-09-28", type:"Loader", eq:"LD-01", operator:"OP-116", shift:"B Shift", norm:190, actual:245, fuelPoint:"Fuel Point-02", status:"Pending", action:"Inspect Machine", remarks:"Higher than last exception"},
  {date:"2026-09-29", type:"Dumper", eq:"DT-02", operator:"OP-102", shift:"C Shift", norm:240, actual:280, fuelPoint:"Fuel Point-03", status:"Under Inspection", action:"Inspect Machine", remarks:"Repeat exception on this machine"},
  {date:"2026-09-29", type:"Dumper", eq:"DT-07", operator:"OP-115", shift:"B Shift", norm:260, actual:391, fuelPoint:"Fuel Point-02", status:"Pending", action:"Inspect Machine", remarks:"Second operator also above norm"},
  {date:"2026-09-29", type:"Dumper", eq:"DT-08", operator:"OP-114", shift:"B Shift", norm:260, actual:307, fuelPoint:"Fuel Point-02", status:"Pending", action:"Check Fuel Issue", remarks:"Awaiting hour-meter check"},
  {date:"2026-09-29", type:"Dumper", eq:"DT-08", operator:"OP-114", shift:"C Shift", norm:260, actual:243, fuelPoint:"Fuel Point-02", status:"Closed", action:"No Action", remarks:"Within norm"},
  {date:"2026-09-29", type:"Dozer", eq:"DZ-01", operator:"OP-118", shift:"A Shift", norm:260, actual:324, fuelPoint:"Fuel Point-04", status:"Pending", action:"Maintenance Check", remarks:"Repeat pattern; check engine"},
  {date:"2026-09-30", type:"Dumper", eq:"DT-02", operator:"OP-101", shift:"B Shift", norm:240, actual:213, fuelPoint:"Fuel Point-03", status:"Closed", action:"No Action", remarks:"Within norm"},
  {date:"2026-09-30", type:"Dumper", eq:"DT-04", operator:"OP-103", shift:"A Shift", norm:240, actual:362, fuelPoint:"Fuel Point-02", status:"Pending", action:"Check Fuel Issue", remarks:"Single very high fuel issue; verify hour-meter"}
];
